apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: citizens-demo-camel-s3-serverless
  title: Citizens Demo - Camel S3 Serverless
  description: |
    Event-Driven Microservices with Camel & Quarkus
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - camel
    - quarkus
spec:
  type: module
  lifecycle: production
  owner: group:default/cluster-admins
  subcomponentOf: component:default/citizens-demo-camel-s3-serverless
